# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Dev

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build Website
    runs-on: windows-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      - name: Copy .env.example
        run: |
          if (-not (Test-Path .env)) {
            Copy-Item .env.example .env
          } else {
            Write-Host ".env file already exists. Skipping the copy step."
          }
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # 上传构建产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Home
          path: dist

  push-to-output-branch:
    name: Push dist to output branch
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Home
          path: dist

      - name: Create orphan branch and add files
        run: |
          git checkout --orphan output
          git rm -rf .
          cp -r dist/* .
          rm -rf dist

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update output branch with dist files"
          git push -f origin output
